{
 "title": "Hargassner Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Aussentemperatur",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: ${__from:date}, stop: ${__to:date})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NanoPK_25\")\n  |> filter(fn: (r) => r[\"slug\"] == \"nanopk-25\")\n  |> filter(fn: (r) => r[\"_field\"] == \"outdoor_temperature\" or r[\"_field\"] == \"outdoor_temperature_average\")\n"
    }
   ]
  },
  { "title": "Kessel-Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Puffertemperaturen",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: ${__from:date}, stop: ${__to:date})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BUFFER\")\n  |> filter(fn: (r) => r[\"slug\"] == \"nanopk-25\")\n  |> filter(fn: (r) => r[\"_field\"] == \"buffer_temperature_bottom\" or r[\"_field\"] == \"max_requirement\" or r[\"_field\"] == \"buffer_temperature_center\" or r[\"_field\"] == \"buffer_temperature_top\")"
    }
   ]
  },
  {
   "title": "Heizungskessel Temperaturen",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: ${__from:date}, stop: ${__to:date})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NanoPK_25\")\n  |> filter(fn: (r) => r[\"slug\"] == \"nanopk-25\")\n  |> filter(fn: (r) => r[\"_field\"] == \"heater_temperature_current\" or r[\"_field\"] == \"heater_temperature_target\" or r[\"_field\"] == \"smoke_temperature\")\n"
    }
   ]
  },
  {
   "title": "Pufferfüllgrad & Kesselleistung",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: ${__from:date}, stop: ${__to:date})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BUFFER\")\n  |> filter(fn: (r) => r[\"slug\"] == \"nanopk-25\")\n  |> filter(fn: (r) => r[\"_field\"] == \"buffer_charge\")"
    },
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: ${__from:date}, stop: ${__to:date})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NanoPK_25\")\n  |> filter(fn: (r) => r[\"slug\"] == \"nanopk-25\")\n  |> filter(fn: (r) => r[\"_field\"] == \"efficiency\")\n"
    }
   ]
  },
  {
   "title": "Pufferpumpe & Kesselstatus",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: ${__from:date}, stop: ${__to:date})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BUFFER\")\n  |> filter(fn: (r) => r[\"slug\"] == \"nanopk-25\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pump_active\")\n\n"
    },
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: ${__from:date}, stop: ${__to:date})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NanoPK_25\")\n  |> filter(fn: (r) => r[\"slug\"] == \"nanopk-25\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\" )"
    }
   ]
  },
  { "title": "Solaranlage-Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Puffertemperaturen",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: ${__from:date}, stop: ${__to:date})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BUFFER\")\n  |> filter(fn: (r) => r[\"slug\"] == \"nanopk-25\")\n  |> filter(fn: (r) => r[\"_field\"] == \"buffer_temperature_bottom\" or r[\"_field\"] == \"buffer_temperature_center\" or r[\"_field\"] == \"buffer_temperature_top\")"
    }
   ]
  },
  {
   "title": "Solaranlage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: ${__from:date}, stop: ${__to:date})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DIFFERENCE_CONTROLLER\")\n  |> filter(fn: (r) => r[\"slug\"] == \"nanopk-25\")\n  |> filter(fn: (r) => r[\"_field\"] == \"source_temperature\" or r[\"_field\"] == \"target_1_temperature\")\n"
    },
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: ${__from:date}, stop: ${__to:date})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DIFFERENCE_CONTROLLER\")\n  |> filter(fn: (r) => r[\"slug\"] == \"nanopk-25\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pump_active\")\n"
    }
   ]
  },
  {
   "title": "Solaranlanlage Leistung & Ertrag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: ${__from:date}, stop: ${__to:date})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DIFFERENCE_CONTROLLER\")\n  |> filter(fn: (r) => r[\"slug\"] == \"nanopk-25\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\" or r[\"_field\"] == \"power_counter_day\")\n"
    }
   ]
  },
  {
   "title": "Deprecated",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heizungskessel Status & Leistung",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"heizung\")\n  |> range(start: ${__from:date}, stop: ${__to:date})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NanoPK_25\")\n  |> filter(fn: (r) => r[\"slug\"] == \"nanopk-25\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\" )\n"
      },
      {
       "query": "from(bucket: \"heizung\")\n  |> range(start: ${__from:date}, stop: ${__to:date})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NanoPK_25\")\n  |> filter(fn: (r) => r[\"slug\"] == \"nanopk-25\")\n  |> filter(fn: (r) => r[\"_field\"] == \"efficiency\")\n"
      }
     ]
    },
    {
     "title": "Puffer Füllgrad & Pumpe",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 9, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"heizung\")\n  |> range(start: ${__from:date}, stop: ${__to:date})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BUFFER\")\n  |> filter(fn: (r) => r[\"slug\"] == \"nanopk-25\")\n  |> filter(fn: (r) => r[\"_field\"] == \"buffer_charge\")"
      },
      {
       "query": "from(bucket: \"heizung\")\n  |> range(start: ${__from:date}, stop: ${__to:date})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BUFFER\")\n  |> filter(fn: (r) => r[\"slug\"] == \"nanopk-25\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pump_active\")"
      }
     ]
    },
    {
     "title": "Pellets Füllstand [kg]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 1, "y": 60 },
     "targets": [
      {
       "query": "from(bucket: \"heizung\")\n  |> range(start: ${__from:date}, stop: ${__to:date})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NanoPK_25\")\n  |> filter(fn: (r) => r[\"slug\"] == \"nanopk-25\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fuel_stock\")\n"
      }
     ]
    },
    {
     "title": "Pellets Füllstand [kg]",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 11, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"heizung\")\n  |> range(start: ${__from:date}, stop: ${__to:date})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NanoPK_25\")\n  |> filter(fn: (r) => r[\"slug\"] == \"nanopk-25\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fuel_stock\")\n"
      }
     ]
    }
   ]
  }
 ]
}