{
 "title": "Pelletslager",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Pellets Füllstand [kg]",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: ${__from:date}, stop: ${__to:date})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NanoPK_25\")\n  |> filter(fn: (r) => r[\"slug\"] == \"nanopk-25\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fuel_stock\")\n"
    }
   ]
  },
  {
   "title": "Pelletslager Füllstand [kg]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NanoPK_25\")\n  |> filter(fn: (r) => r[\"slug\"] == \"nanopk-25\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fuel_stock\")\n\n"
    }
   ]
  },
  {
   "title": "Pelletsverbrauch pro Tag [kg]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"heizung\")\n  |> range(start: ${__from:date}, stop: ${__to:date})\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NanoPK_25\")\n  |> filter(fn: (r) => r[\"slug\"] == \"nanopk-25\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fuel_stock\")\n  |> aggregateWindow(every: 1d, fn: last)\n  |> difference()\n  |> map(fn: (r) => ({ r with _value: r._value * -1.0 })) \n\n"
    }
   ]
  }
 ]
}